#!/usr/bin/env node

const fs = require('fs');
const path=require('path')

const shell=require('shelljs')

function walkSync(currentDirPath, callback) {
    fs.readdirSync(currentDirPath).forEach(function (name) {
        var filePath = path.join(currentDirPath, name);
        var stat = fs.statSync(filePath);
        if (stat.isFile()) {
            callback(filePath, stat);
        } else if (stat.isDirectory()) {
            walkSync(filePath, callback);
        }
    });
}

function getNewPath(path){
    const tmp=path.split('/')
    const fileName=tmp.pop()
    newFileName=fileName.replace('aabb','')
    return tmp.join('/')+'/'+newFileName
}
;(function(){
    const [nodeEnv,dir,...args]=process.argv
    // 获取用户输入的路径
    const folder=args[0]
    if(!folder)throw Error('请提供文件夹路径!')
    walkSync(folder,(filePath,stat)=>{
        //重命名操作： 1aabb.html -> 1.html 即去除aabb
        shell.exec(`mv ${filePath} ${getNewPath(filePath)}`)
    })
}())
